services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8050:8050"
    env_file:
      - .env.prod
    depends_on:
      - oracle
    links:
      - oracle
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health"] # Đảm bảo endpoint này tồn tại
      interval: 30s
      timeout: 10s
      retries: 3

  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: "duc140603"
      APP_USER: "graphicproduction"
      APP_USER_PASSWORD: "duc140603"
    ports:
      - "1523:1523"
    volumes:
      # - ./listener.ora:/opt/oracle/product/23ai/dbhomeFree/network/admin/listener.ora
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "tnsping", "oracle:1523"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
